# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# GRUB configuration tasks

- name: Remove GRUB_CMDLINE_LINUX_DEFAULT option in grub conf
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    state: absent
  when: grub_remove_default | default(false)

- name: Remove quiet from GRUB_CMDLINE_LINUX_DEFAULT option in grub conf
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\")(.*?[ ])?quiet([ ].*)?(\")$"
    line: '\1\2\3\4'
    backrefs: yes
  notify: "{{ grub_update_handler }}"
  when: grub_remove_quiet | default(false)

- name: Make sure GRUB_CMDLINE_LINUX_DEFAULT has no double space
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)[ ][ ](.*\")"
    line: '\1 \2'
    state: present
    backrefs: yes
  register: doublespace
  until: not doublespace.changed
  delay: 1
  retries: 10
  when: grub_remove_quiet | default(false)

- name: Make sure GRUB_CMDLINE_LINUX exists 1/2
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX=\".*\""
    state: absent
  check_mode: true
  changed_when: false
  register: check_grub_cmdline_linux
  when: grub_ensure_linux_exists | default(false)

- name: Make sure GRUB_CMDLINE_LINUX exists 2/2
  lineinfile:
    path: /etc/default/grub
    state: present
    line: "GRUB_CMDLINE_LINUX=\" \""
  when: 
    - grub_ensure_linux_exists | default(false)
    - check_grub_cmdline_linux.found == 0

- name: Make sure GRUB_CMDLINE_LINUX starts with a space
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=)\"([ ]*)(.*)\""
    line: '\1" \3"'
    state: present
    backrefs: yes

- name: Configure GRUB kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]*)(\".*)"
    line: '\1 {{ item }}\2'
    state: present
    backrefs: yes
  notify: "{{ grub_update_handler }}"
  with_items: "{{ grub_kernel_params }}"

- name: Grub conf osprober
  lineinfile:
    dest: /etc/default/grub
    regexp: '^#?GRUB_DISABLE_OS_PROBER=.*$'
    line: 'GRUB_DISABLE_OS_PROBER=true'
    state: present
  notify: "{{ grub_update_handler }}"
