# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Include OS family-specific variables
- include_vars: "{{ ansible_os_family }}.yml"

# System logging configuration
- name: Configure logging
  include_tasks: logging_config.yml

# User management
- name: Configure user management
  include_tasks: user_management.yml

# System configuration
- name: Configure system settings
  include_tasks: system_config.yml

# Vim configuration
- name: Configure vim
  include_tasks: vim_config.yml

# GRUB configuration
- name: Configure GRUB
  include_tasks: grub_config.yml

# Network management
- name: Configure network services
  include_tasks: network_config.yml

# Package management (Debian only)
- name: Configure APT repositories
  include_tasks: apt_config.yml
  when:
    - manage_apt_repos | default(false)
    - ansible_os_family == "Debian"
