# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Network configuration tasks

- name: Stop and Disable NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no
  register: nm_stop
  when: network_disable_nm | default(true)

- name: Start and Enable systemd-networkd
  service:
    name: systemd-networkd
    state: started
    enabled: yes
  register: sd_start
  when: network_enable_networkd | default(true)

- name: Set need_reboot to true if any change was made
  set_fact:
    need_reboot: true
  when: 
    - network_disable_nm | default(true)
    - network_enable_networkd | default(true)
    - (nm_stop is changed or sd_start is changed)

- name: Disable PerSourcePenalties
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PerSourcePenalties.*$'
    line: 'PerSourcePenalties no'
    state: present
  notify: Restart sshd
  when: ssh_disable_per_source_penalties | default(false)

# SR-IOV network configuration
- name: Add SR-IOV sysfs rules
  template:
    src: sriov.conf.j2
    dest: /etc/tmpfiles.d/sriov.conf
    mode: '0644'
  with_items: "{{ sriov | dict2items }}"
  when: sriov is defined
  register: sriov_tmpfiles

- name: Copy workqueue cpumask configuration
  template:
    src: tmpfiles-workqueue_cpumask.conf.j2
    dest: /etc/tmpfiles.d/tmpfiles-workqueue_cpumask.conf
    mode: '0644'
  register: tmpfiles_cpumask
