# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Yocto family specific variables for system tuning

# GRUB configuration (Yocto doesn't use GRUB)
grub_update_handler: "Update Grub"
grub_update_command: "grub2-mkconfig -o /boot/grub2/grub.cfg"

# Yocto-specific variables
yocto_config_file: "/boot/extlinux/extlinux.conf"
soft_restart_command: "systemctl reboot"
