---
# Converge playbook for debian_hypervisor role testing

- name: Pre-converge workarounds
  hosts: all
  become: true
  tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: true

- name: Converge
  hosts: all
  become: true
  roles:
    - role: debian_hypervisor
