# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  author: "Seapath"
  description: "Libvirt service management and configuration"
  license: Apache-2.0
  min_ansible_version: 2.9.10
  platforms:
    - name: EL
      versions: [all]
    - name: Debian
      versions: [all]
    - name: Yocto
      versions: [all]
  galaxy_tags:
    - virtualization
    - libvirt
    - seapath
dependencies:
  - role: system_base
