# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Debian/Ubuntu specific variables for system_hardening

# OpenSCAP packages for Debian
openscap_packages:
  - openscap-scanner
  - ssg-base
  - ssg-debderived
  - ssg-debian
  - ssg-nondebian
  - ssg-applications

# Distribution-specific paths
sudoers_path: /etc/sudoers
grub_password_path: /etc/grub.d/01_password
grub_update_command: update-grub

# SCAP datastream path
scap_datastream_path: "/usr/share/xml/scap/ssg/content/ssg-debian{{ ansible_distribution_major_version }}.xml"
scap_datastream_fallback: "/usr/share/xml/scap/ssg/content/ssg-debian.xml"

# Services to harden on Debian (OVS hardening moved to openvswitch role)
hardened_services:
  - syslog-ng
  - corosync
  - pacemaker
  - ceph-crash
