# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Configure Pacemaker service

- name: Create pacemaker.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/pacemaker.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Pacemaker service override
  ansible.builtin.template:
    src: pacemaker_override.conf.j2
    dest: /etc/systemd/system/pacemaker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: Trigger daemon-reload
  register: pacemaker_config

- name: Get Pacemaker service status
  ansible.builtin.systemd:
    name: "pacemaker.service"
  register: pacemaker_service_status

- name: Disable pacemaker (reinstall step 1/2)
  ansible.builtin.systemd:
    name: pacemaker.service
    enabled: no
  when: pacemaker_config.changed and pacemaker_service_status.status.UnitFileState == "enabled"

- name: Enable pacemaker (reinstall step 2/2)
  ansible.builtin.systemd:
    name: pacemaker.service
    enabled: yes
  when: pacemaker_config.changed and pacemaker_service_status.status.UnitFileState == "enabled"
