---
# Converge playbook for network_resolved role testing

- name: Pre-converge workarounds
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

- name: Converge
  hosts: all
  become: true
  roles:
    - role: network_resolved
