# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Include OS family-specific variables
- include_vars: "{{ ansible_os_family }}.yml"

# Kernel parameters configuration
- name: Configure kernel parameters
  include_tasks: kernel_params.yml

# Kernel modules and sysctl configuration
- name: Configure kernel modules
  include_tasks: kernel_modules.yml

# Sysctl configuration
- name: Configure sysctl parameters
  include_tasks: sysctl_config.yml

# Hugepages configuration (performance tuning)
- name: Configure hugepages
  include_tasks: hugepages_config.yml
