# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Real-time tuning configuration

- name: Install tuned packages for RedHat
  ansible.builtin.dnf:
    name:
      - tuned
      - tuned-profiles-nfv
      - tuned-profiles-realtime
    state: present
  when: ansible_os_family == "RedHat"

- name: Install tuned packages for Debian
  ansible.builtin.apt:
    name:
      - tuned
      - tuned-utils
    state: present
  when: ansible_os_family == "Debian"

- name: Remove old isolation files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/sysfs.d/00-workqueue_cpumask.conf
    - /etc/systemd/system/kthread-taskset.service
    - /usr/local/bin/taskset_boot.sh
    - /etc/systemd/system/multi-user.target.wants/kthread-taskset.service
    - /etc/sysctl.d/00-schedrt.conf
    - /etc/default/grub.d/10-isolcpus.cfg

- name: Create tuned seapath-rt profile directory
  file:
    path: /etc/tuned/seapath-rt-host
    state: directory
    mode: '0755'

- name: Copy seapath-rt-host tuned profile configuration
  template:
    src: tuned.conf.j2
    dest: /etc/tuned/seapath-rt-host/tuned.conf
    group: root
    owner: root
    mode: '0644'

- name: Disable tuned dynamic tuning
  lineinfile:
    path: /etc/tuned/tuned-main.conf
    state: present
    regexp: '^#?dynamic_tuning = .*$'
    line: 'dynamic_tuning = 0'

- name: Enable tuned service
  ansible.builtin.systemd:
    name: tuned.service
    enabled: yes
    state: restarted

- name: Load seapath-rt-host tuned profile
  ansible.builtin.command: tuned-adm profile seapath-rt-host
  when: isolcpus is defined
  changed_when: true

- name: Unload tuned profile
  ansible.builtin.command: tuned-adm off
  when: isolcpus is not defined
  changed_when: true

- name: Copy OVS vswitchd systemd override
  ansible.builtin.copy:
    src: systemd/system/ovs-vswitchd.service.d/override.conf
    dest: /etc/systemd/system/ovs-vswitchd.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: Start new slices
