# Copyright (C) 2025 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  role_name: network_nmstate
  description: Configure network using NMState on RedHat-family systems
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
