# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Debian family specific tasks

- name: Configure Pacemaker Seapath resources
  when: "'cluster_machines' in group_names"
  block:

    - name: Copy Pacemaker Seapath Resource-Agent files
      ansible.posix.synchronize:
        src: pacemaker_ra/
        dest: /usr/lib/ocf/resource.d/seapath/
        rsync_opts:
          - "--chmod=F755"
          - "--chown=root:root"

    - name: Copy VirtualDomain from heartbeat to seapath
      copy:
        remote_src: yes
        src: /usr/lib/ocf/resource.d/heartbeat/VirtualDomain
        dest: /usr/lib/ocf/resource.d/seapath/VirtualDomain
        owner: root
        group: root
        mode: '0755'
        force: yes

    - name: Apply patch to VirtualDomain
      ansible.posix.patch:
        src: VirtualDomain_patch
        dest: /usr/lib/ocf/resource.d/seapath/VirtualDomain
        strip: 0

    - name: Copy ethmonitor from heartbeat to seapath
      copy:
        remote_src: yes
        src: /usr/lib/ocf/resource.d/heartbeat/ethmonitor
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        owner: root
        group: root
        mode: '0755'
        force: yes

    - name: Apply patch1 to ethmonitor
      ansible.posix.patch:
        src: ethmonitor_patch1
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        strip: 0

    - name: Apply patch2 to ethmonitor
      ansible.posix.patch:
        src: ethmonitor_patch2
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        strip: 0

- when:
    - services['pacemaker.service'] is defined
  block:
    - name: Create pacemaker.service.d directory
      file:
        path: /etc/systemd/system/pacemaker.service.d/
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Copy pacemaker.service drop-in
      template:
        src: pacemaker_override.conf.j2
        dest: /etc/systemd/system/pacemaker.service.d/override.conf
        owner: root
        group: root
        mode: 0644
      notify: Trigger daemon-reload
      register: pacemaker_corosync
    - name: Get Pacemaker service Status
      ansible.builtin.systemd:
        name: "pacemaker.service"
      register: pacemaker_service_status
    - name: Disable pacemaker (reinstall step 1/2)
      ansible.builtin.systemd:
        name: pacemaker.service
        enabled: no
      when: pacemaker_corosync.changed and pacemaker_service_status.status.UnitFileState == "enabled"
    - name: Enable pacemaker (reinstall step 2/2)
      ansible.builtin.systemd:
        name: pacemaker.service
        enabled: yes
      when: pacemaker_corosync.changed and pacemaker_service_status.status.UnitFileState == "enabled"

- name: Add extra modules to the kernel
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: "^{{ item }}$"
    line: "{{ item }}"
  with_items: "{{ extra_kernel_modules | default([]) }}"

- name: Add br_netfilter to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^br_netfilter$'
    line: 'br_netfilter'

- name: Add raid6_pq to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^raid6_pq$'
    line: 'raid6_pq'

- name: Configure initramfs-tools to use busybox
  lineinfile:
    dest: /etc/initramfs-tools/initramfs.conf
    regexp: "^#?BUSYBOX="
    line: "BUSYBOX=y"
    state: present
  notify: Rebuild initramfs if necessary

- name: Add udev rules for lvm2 limitation
  ansible.builtin.copy:
    src: 69-lvm.rules
    dest: /etc/udev/rules.d/69-lvm.rules
    mode: '0644'
  when: ansible_distribution == 'Debian' and ansible_distribution_version | int >= 12
  register: udevlvm

- name: Ensure group www-data exists with GID 1033
  group:
    name: www-data
    gid: 1033
    state: present

- name: Ensure user www-data exists with UID 1033 and GID 1033
  user:
    name: www-data
    uid: 1033
    group: www-data
    shell: /bin/bash
