# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Debian family specific tasks

# Cluster-related tasks moved to cluster_* roles

- name: Add extra modules to the kernel
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: "^{{ item }}$"
    line: "{{ item }}"
  with_items: "{{ extra_kernel_modules | default([]) }}"

- name: Add br_netfilter to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^br_netfilter$'
    line: 'br_netfilter'

- name: Add raid6_pq to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^raid6_pq$'
    line: 'raid6_pq'

- name: Configure initramfs-tools to use busybox
  lineinfile:
    dest: /etc/initramfs-tools/initramfs.conf
    regexp: "^#?BUSYBOX="
    line: "BUSYBOX=y"
    state: present
  notify: Rebuild initramfs if necessary

- name: Add udev rules for lvm2 limitation
  ansible.builtin.copy:
    src: 69-lvm.rules
    dest: /etc/udev/rules.d/69-lvm.rules
    mode: '0644'
  when: ansible_distribution == 'Debian' and ansible_distribution_version | int >= 12
  register: udevlvm

- name: Ensure group www-data exists with GID 1033
  group:
    name: www-data
    gid: 1033
    state: present

- name: Ensure user www-data exists with UID 1033 and GID 1033
  user:
    name: www-data
    uid: 1033
    group: www-data
    shell: /bin/bash
