# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Handlers for system_tuning role

- name: Restart hugepages service
  ansible.builtin.systemd:
    name: hugepages.service
    state: restarted

- name: Start new slices
  ansible.builtin.systemd:
    name: "{{ item }}.slice"
    state: restarted
    daemon_reload: yes
  with_items:
    - "machine-rt"
    - "machine-nort"
    - "ovs"

- name: Start new slices REVERT
  ansible.builtin.systemd:
    name: "{{ item }}.slice"
    state: stopped
    daemon_reload: yes
  with_items:
    - "machine-rt"
    - "machine-nort"
    - "ovs"

- name: Restart irqbalance
  ansible.builtin.systemd:
    name: irqbalance.service
    enabled: yes
    state: restarted
