# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook configures and sets up Ceph with cephadm using a pure declarative approach.
# All disk preparation, LVM expansion, and OSD management is handled declaratively by cephadm.

---

- name: Cephadm Cluster Setup with Declarative LVM Management
  hosts:
      cluster_machines
  become: true
  gather_facts: yes
  roles:
    - detect_seapath_distro
    - cephadm
  vars:
    registry_url: "{{ registry_url | default('localhost:5000') }}"
    registry_host: "{{ registry_host | default('localhost') }}"
