# Copyright (C) 2022, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# Ansible playbook that creates the cluster by configuring Corosync and
# Pacemaker.

---
- name: Configure HA basics
  hosts: cluster_machines
  become: true
  vars:
    corosync_node_list: "{{ groups['cluster_machines'] | list }}"
  roles:
    - detect_distribution
    - cluster_corosync
    - cluster_pacemaker
    - cluster_setup
