# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Create and start VMs
  hosts: standalone_machine
  gather_facts: false
  become: true
  vars:
    vm_disk_pool: "/var/lib/libvirt/images"
    vm_disk_copy: true
  roles:
    - virtualization_vms

- name: Wait for VMs to be online
  hosts: VMs
  gather_facts: false
  tasks:
    - name: Wait for VM connections
      ansible.builtin.wait_for_connection:
      when: wait_for_connection | default(false)
