# Copyright (C) 2021, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
# Deploy all VMs define in the VMs group

---
- name: Deploy VMs on cluster
  hosts: "{{ groups.cluster_machines[0] }}"
  gather_facts: false
  become: true
  roles:
    - virtualization_vms
