# Copyright (C) 2020, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This Ansible playbook configures the networks and defines the hostnames.

---
- name: Network configuration
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  gather_facts: true
  vars_files:
    - "../vars/network_team0.yml"
  pre_tasks:
    - name: Dynamically include network configuration variables
      include_vars:
        file: "../vars/network_{{ 'empty' if netplan_configurations is defined or (network_simple is defined and network_simple) else 'defaults' }}.yml"
  roles:
    - detect_distribution
    - system_base
    - role: systemd_networkd
      vars:
        systemd_networkd_apply_config: "{{ apply_network_config | default(false) }}"
      when: netplan_configurations is not defined

- name: Configure Open vSwitch and cluster network
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  roles:
    - role: openvswitch
      vars:
        network_configovs_apply_config: "{{ apply_network_config | default(false) }}"
      when: no_cluster_network is not defined

- name: Configure sriov libvirt network pool
  hosts:
    - hypervisors
  become: true
  tasks:
    - name: Calling sriov network pool creation (with a loop)
      include_role:
        name: network_sriovpool
      vars:
        network_sriovpool_interface: "{{ item.key }}"
        network_sriovpool_sriov_network_pool_name: "{{ 'sr-iov-net-' + item.key }}"
      loop: "{{ sriov | dict2items }}"
      when: sriov is defined

- name: Push iptables rules
  hosts:
    - cluster_machines
    - standalone_machine
  roles:
    - iptables

- name: Configure VM networking and deployment
  become: true
  hosts:
    - cluster_machines
    - standalone_machine
  roles:
    - virtualization_vms

- name: Conntrackd
  hosts: cluster_machines
  become: true
  roles:
    - role: cluster_conntrackd
      when: conntrackd_ignore_ip_list is defined

- name: Restart machine if needed
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  tasks:
    - when:
        - need_reboot is defined and need_reboot
        - skip_reboot_setup_network is not defined or not skip_reboot_setup_network
      block:
        - name: Restart to configure network
          reboot:
        - name: Wait for host to be online
          wait_for_connection:
