# Copyright (C) 2024 Red Hat, Inc.
# Copyright (C) 2021-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This playbook setup SEAPATH on both debian and CentOS machines
# The machine must previously have been flashed
# with an iso created by build_debian_iso or CentOS with appropriate kickstart file
# This playbooks can also configure VMs created with build_debian_iso
# This playbook also configures Yocto standalone machine (no cluster)

- name: Detect Seapath distribution
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  roles:
    - detect_distribution

- name: Import seapath_setup_prerequisites playbook
  import_playbook: seapath_setup_prerequisites.yaml

- name: Import seapath_setup_cockpit_plugins playbook
  import_playbook: seapath_setup_cockpit_plugins.yaml
  when: ansible_os_family != "Yocto"

- name: Import seapath_setup_prerequisyocto playbook
  import_playbook: seapath_setup_prerequisyocto.yaml
  when: ansible_os_family == "Yocto"

- name: Import seapath_setup_network playbook
  import_playbook: seapath_setup_network.yaml

- name: Import seapath_setup_timemaster playbook
  import_playbook: seapath_setup_timemaster.yaml

- name: Import seapath_setup_snmp playbook
  import_playbook: seapath_setup_snmp.yaml

- name: Import cluster_setup_ceph playbook
  import_playbook: cluster_setup_ceph.yaml
  when: not is_using_cephadm | bool

- name: Import cluster_setup_cephdm playbook
  import_playbook: cluster_setup_cephadm.yaml
  when: is_using_cephadm | bool

- name: Import cluster_setup_libvirt playbook
  import_playbook: cluster_setup_libvirt.yaml
- name: Import cluster_setup_users playbook
  import_playbook: cluster_setup_users.yaml
- name: Import cluster_setup_ha playbook
  import_playbook: cluster_setup_ha.yaml
- name: Import seapath_setup_vmmgrapi playbook
  import_playbook: seapath_setup_vmmgrapi.yaml

- name: Restart all hosts
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  tasks:
    - name: Restart to configure SEAPATH
      reboot:
      when:
        - skip_reboot_setup is not defined or not skip_reboot_setup
    - name: Wait for host to be online
      wait_for_connection:
