# Copyright (C) 2022, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Deploy Cukinia's tests
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  gather_facts: True
  roles:
    - deploy_cukinia
    - detect_distribution

- name: Deploy Cukinia's tests
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  gather_facts: True
  roles:
    - role: debian_tests
      when: ansible_os_family == "Debian"
    - role: oraclelinux_tests
      when: ansible_os_family == "RedHat"
