# Copyright (C) 2024 RTE
# Copyright (C) 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0

---
# CentOS Hypervisor Role - Virtualization-specific tasks only
# CPU isolation and real-time tuning moved to system_tuning role

- name: Enable libvirtd.service
  ansible.builtin.systemd:
    name: libvirtd.service
    enabled: yes
    state: started

- name: Create system alternative for a debian kvm path
  community.general.alternatives:
    name: "debian kvm"
    path: "/usr/libexec/qemu-kvm"
    link: "/usr/bin/qemu-system-x86_64"