# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
# Debian Hypervisor Role - Virtualization-specific tasks only
# CPU isolation and real-time tuning moved to system_tuning role

- name: Ensure SHUTDOWN_TIMEOUT is set to 20 #for Standalone
  ansible.builtin.lineinfile:
    path: /etc/default/libvirt-guests
    regexp: '^#?SHUTDOWN_TIMEOUT=.*'
    line: 'SHUTDOWN_TIMEOUT=20'